modLoader="javafml"
loaderVersion="[37,)"
license="MIT"
[[mods]]
    modId="morefood"
    version="${file.jarVersion}"
    displayName="More Food"
    authors="LegibleSleet827"
    description='''
    This mod adds more food to minecraft, ranging from small things like chicken nuggets, to big ones like burgers and pizzas.
    '''

[[dependencies.morefood]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.morefood]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
